/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package romanow.abc.desktop.wizard;

import lombok.Setter;
import romanow.abc.core.constants.ConstValue;
import romanow.abc.core.constants.Values;
import romanow.abc.core.entity.metadata.Meta2Entity;
import romanow.abc.desktop.I_Value;
import romanow.abc.desktop.MainBaseFrame;

import javax.swing.*;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.HashMap;

/**
 *
 * @author romanow0
 */
public class WizardBaseView extends javax.swing.JFrame {
    @Setter private I_Value<String> onClose=null;
    protected MainBaseFrame main;
    protected WizardBaseView parentView;
    protected Meta2Entity entity;
    protected int level=0;
    protected I_Value<String> back;
    public static String openWizard(MainBaseFrame main0, Meta2Entity entity,I_Value<String> back){
        String name = "Wizard"+entity.getClass().getSimpleName();
        try {
            Class  cls = Class.forName("romanow.abc.desktop.wizard."+name);
            WizardBaseView view = (WizardBaseView)cls.newInstance();
            view.back = back;
            view.main = main0;
            view.openForm(null,entity);
            view.revalidate();
            view.repaint(1000);
            return null;
            } catch (Exception ee){
                return "Ошибка создания формы "+name+": "+ee.toString();
                }
            }
    public String openWizardByType(Meta2Entity entity){
        return openWizardByType(entity,this,null,null);
        }
    public static String openWizardByType(Meta2Entity entity,WizardBaseView parent, I_Value<String> closeCode,I_Value<String> back0){
        String name = "Wizard"+entity.getClass().getSimpleName();
        try {
            Class  cls = Class.forName("romanow.abc.desktop.wizard."+name);
            WizardBaseView view = (WizardBaseView)cls.newInstance();
            view.setOnClose(closeCode);
            view.back = back0;
            view.openForm(parent,entity);
            view.revalidate();
            view.repaint(1000);
            return null;
            } catch (Exception ee){
                return "Ошибка создания формы "+name+": "+ee.toString();
                }
        }

    public void openForm(WizardBaseView parentView0,Meta2Entity entity0) {
        level = parentView0==null ? 0 : level+1;
        parentView = parentView0;
        if (parentView !=null){
            main = parentView.main;
            back = parentView.back;
            parentView.setVisible(false);
            }
        entity = entity0;
        setVisible(true);
        setLocation(200+level*10,250+level*10);
        setTitle("Уровень "+(level+1)+"  "+entity.getFullTitle());
        Title.setText(entity.getTitle());
        Comment.setText(entity.getComment());
        ShortName.setText(entity.getShortName());
        }

    public WizardBaseView(){
        initComponents();
        setVisible(true);
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ShortName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Comment = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Title = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        ShortName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ShortNameKeyPressed(evt);
            }
        });
        getContentPane().add(ShortName);
        ShortName.setBounds(60, 10, 80, 25);

        jLabel1.setText("Название");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 15, 70, 14);

        Comment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CommentKeyPressed(evt);
            }
        });
        getContentPane().add(Comment);
        Comment.setBounds(100, 50, 530, 25);

        jLabel2.setText("Комментарий");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 55, 100, 14);

        jLabel3.setText("Имя ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 15, 40, 14);

        Title.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TitleKeyPressed(evt);
            }
        });
        getContentPane().add(Title);
        Title.setBounds(230, 10, 400, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void closeForm(){
        if (parentView!=null)
            parentView.setVisible(true);
        if (onClose!=null)
            onClose.onEnter(entity.getTitle());
        dispose();
    }

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        closeForm();
    }//GEN-LAST:event_formWindowClosing

    private void ShortNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ShortNameKeyPressed
        onStringKeyPressed("shortName", ShortName, evt, new I_WizardActionString() {
            @Override
            public void onAction(String value) {
                entity.setShortName(value);
            }
        });
    }//GEN-LAST:event_ShortNameKeyPressed

    private void TitleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TitleKeyPressed
        onStringKeyPressed("title", Title, evt, new I_WizardActionString() {
            @Override
            public void onAction(String value) {
                entity.setTitle(value);
            }
        });
    }//GEN-LAST:event_TitleKeyPressed

    private void CommentKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CommentKeyPressed
        onStringKeyPressed("comment", Comment, evt, new I_WizardActionString() {
            @Override
            public void onAction(String value) {
                entity.setComment(value);
            }
        });
    }//GEN-LAST:event_CommentKeyPressed


    public void onKeyPressed(String name, JTextField fld, KeyEvent evt, I_WizardAction action){
        if(evt.getKeyCode()!=10) return;
        int xx=0;
        try {
            xx = Integer.parseInt(fld.getText());
            action.onAction(xx);
            if (evt!=null)
                main.viewUpdate(evt,true);
            back.onEnter("Изменено "+name+": "+fld.getText());
        } catch (Exception ee){
            System.out.println("Ошибка целого: "+fld.getText());
            if (evt!=null)
                main.viewUpdate(evt,false);
        }
    }
    public void onKeyPressed(String name, JCheckBox hex, JTextField fld, KeyEvent evt, I_WizardAction action){
        if(evt.getKeyCode()!=10) return;
        int xx=0;
        String ss = fld.getText();
        try {
            if (!hex.isSelected())
                xx = Integer.parseInt(ss);
            else{
                xx = Integer.parseInt(ss.startsWith("0x") ? ss.substring(2) : ss,16);
            }
            action.onAction(xx);
            if (evt!=null)
                main.viewUpdate(evt,true);
            back.onEnter("Изменено "+name+": "+fld.getText());
        } catch (Exception ee){
            System.out.println("Ошибка целого: "+fld.getText());
            if (evt!=null)
                main.viewUpdate(evt,false);
        }
    }
    public void onColorKeyPressed(String name,JTextField fld, JButton button, KeyEvent evt, I_WizardAction action){
        if(evt.getKeyCode()!=10) return;
        long xx=0;
        try {
            xx = Long.parseLong(fld.getText(),16);
            action.onAction((int)xx);
            if (evt!=null)
                main.viewUpdate(evt,true);
            button.setBackground(new Color((int)xx));
            back.onEnter("Изменено "+name+": "+fld.getText());
        } catch (Exception ee){
            System.out.println("Ошибка целого(16): "+fld.getText());
            if (evt!=null)
                main.viewUpdate(evt,false);
        }
    }
    public void onStringKeyPressed(String name,JTextField fld, KeyEvent evt, I_WizardActionString action){
        if(evt.getKeyCode()!=10) return;
        action.onAction(fld.getText());
        if (evt!=null)
            main.viewUpdate(evt,true);
        back.onEnter("Изменено "+name+": "+fld.getText());
    }
    public void onKey16Pressed(String name,JTextField fld, KeyEvent evt, I_WizardAction action){
        if(evt.getKeyCode()!=10) return;
        long xx=0;
        try {
            xx = Long.parseLong(fld.getText(),16);
            action.onAction((int)xx);
            if (evt!=null)
                main.viewUpdate(evt,true);
            back.onEnter("Изменено "+name+": "+fld.getText());
        } catch (Exception ee){
            System.out.println("Ошибка целого(16): "+fld.getText());
            if (evt!=null)
                main.viewUpdate(evt,false);
        }
    }

    public static ArrayList<ConstValue> createEquipElemList(){
        ArrayList<ConstValue> out = new ArrayList<>();
        HashMap<Integer,ConstValue> map = Values.constMap().getGroupMapByValue("MetaElem");
        out.add(map.get(Values.MEDataRegister));
        out.add(map.get(Values.MESetting));
        out.add(map.get(Values.MEBitRegister));
        out.add(map.get(Values.MECommandRegister));
        out.add(map.get(Values.MEStateRegister));
        out.add(map.get(Values.MEArray));
        out.add(map.get(Values.MECollection));
        out.add(map.get(Values.MEBitArray));
        return out;
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Comment;
    private javax.swing.JTextField ShortName;
    private javax.swing.JTextField Title;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
