/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package romanow.abc.desktop.wizard;

import romanow.abc.core.constants.Values;
import romanow.abc.core.entity.EntityRefList;
import romanow.abc.core.entity.subject2area.*;
import romanow.abc.desktop.ESSMetaPanel;

/**
 *
 * @author romanow0
 */
public class WizardESS2EnvValue extends WizardBaseViewDB {

    private ESS2EnvValue envValue;
    private EntityRefList<ESS2ScriptFile> scripts;
    private void selectChoice(){
        for(int i=0;i<scripts.size();i++){
            if (scripts.get(i).getShortName().equals(envValue.getScriptName())){
                ScriptList.select(i+1);
                return;
                }
            ScriptList.select(0);
            }
        }
    public WizardESS2EnvValue(ESSMetaPanel frame0, ESS2Entity entity0, I_Wizard back0) {
        super("Переменная окружения",frame0,entity0,back0);
        initComponents();
        setSize(750,220);
        envValue = (ESS2EnvValue) entity0;
        ScriptName.setText(envValue.getScriptName());
        scripts = panel.getArchitecture().getScripts();
        ScriptList.removeAll();
        ScriptList.add("...");
        for(ESS2ScriptFile scriptFile : scripts)
            ScriptList.add(scriptFile.toString());
        selectChoice();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        ScriptList = new java.awt.Choice();
        SetMetaFile = new javax.swing.JButton();
        ScriptName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(10, 120, 470, 2);
        getContentPane().add(ScriptList);
        ScriptList.setBounds(120, 90, 320, 20);

        SetMetaFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable/save.png"))); // NOI18N
        SetMetaFile.setBorderPainted(false);
        SetMetaFile.setContentAreaFilled(false);
        SetMetaFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetMetaFileActionPerformed(evt);
            }
        });
        getContentPane().add(SetMetaFile);
        SetMetaFile.setBounds(450, 80, 30, 30);

        ScriptName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ScriptNameKeyPressed(evt);
            }
        });
        getContentPane().add(ScriptName);
        ScriptName.setBounds(20, 90, 90, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SetMetaFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetMetaFileActionPerformed
        if (ScriptList.getSelectedIndex()==0){
            main.popup("Не выбран скрипт");
            return;
            }
        ESS2ScriptFile scriptFile = scripts.get(ScriptList.getSelectedIndex()-1);
        if (!(scriptFile.getScriptType()==Values.STCalcOnStart)) {
            main.popup("Недопустимый тип скрипта для переменных окружения");
            return;
            }
        if (!(scriptFile.isPreCompiled())) {
            main.popup("Требуется скрипт с предварительной компиляцией");
            return;
            }
        ScriptName.setText(scriptFile.getShortName());
        envValue.setScriptName(scriptFile.getShortName());
        oneUpdate("Изменено scriptName: "+envValue.getScriptName());
    }//GEN-LAST:event_SetMetaFileActionPerformed

    private void ScriptNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ScriptNameKeyPressed
        onStringKeyPressed("scriptName", ScriptName, evt, new I_WizardActionString() {
            @Override
            public void onAction( String value) {
                envValue.setScriptName(value);
                }
        });
    }//GEN-LAST:event_ScriptNameKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WizardESS2EnvValue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WizardESS2EnvValue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WizardESS2EnvValue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WizardESS2EnvValue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new WizardESS2Connector().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Choice ScriptList;
    private javax.swing.JTextField ScriptName;
    private javax.swing.JButton SetMetaFile;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
