/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package romanow.abc.desktop.wizard;


import romanow.abc.core.constants.ConstValue;
import romanow.abc.core.constants.Values;
import romanow.abc.core.entity.metadata.Meta2Entity;
import romanow.abc.core.entity.metadata.view.Meta2GUI;
import romanow.abc.core.entity.metadata.view.Meta2GUIArray;
import romanow.abc.desktop.I_Button;
import romanow.abc.desktop.OK;

import java.util.ArrayList;
import java.util.Comparator;
import static romanow.abc.core.entity.metadata.view.Meta2GUI.createByType;

/**
 *
 * @author romanow0
 */
public class WizardMeta2GUIArray extends WizardBaseView {
    /**
     * Creates new form xxx
     */
    Meta2GUIArray array;
    ArrayList<ConstValue> types;
    public WizardMeta2GUIArray() {
        initComponents();
        }
    public void openForm(WizardBaseView parentView0, Meta2Entity entity0){
        super.openForm(parentView0,entity0);
        resizeHeight(250);
        array = (Meta2GUIArray) entity;
        if (array.getElem()==null)
            Elem.setText("???");
        else
            Elem.setText(""+array.getElem().getFullTitle());
        DXY.setText(""+array.getDxy());
        Size.setText(""+array.getSize());
        Types.removeAll();
        types = Values.constMap().getGroupList("GUIType");
        types.sort(new Comparator<ConstValue>() {
            @Override
            public int compare(ConstValue o1, ConstValue o2) {
                return o1.title().compareTo(o2.title());
                }
            });
        for(ConstValue cc : types)
            Types.add(cc.title());
        for(int i=0;i<types.size();i++)
            if (types.get(i).value()==array.getElem().getMetaType()) {
                Types.select(i);
                break;
                }
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Elem = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Size = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        DXY = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        ChangeElem = new javax.swing.JButton();
        Edit = new javax.swing.JButton();
        Types = new java.awt.Choice();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        Elem.setEnabled(false);
        getContentPane().add(Elem);
        Elem.setBounds(110, 130, 410, 25);

        jLabel1.setText("Элемент");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 135, 90, 14);

        jLabel3.setText("Размерность");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 95, 100, 14);

        Size.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SizeKeyPressed(evt);
            }
        });
        getContentPane().add(Size);
        Size.setBounds(110, 90, 80, 25);

        jLabel4.setText("Шаг (dxy)");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(200, 95, 60, 14);

        DXY.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DXYKeyPressed(evt);
            }
        });
        getContentPane().add(DXY);
        DXY.setBounds(270, 90, 80, 25);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(10, 82, 560, 2);

        ChangeElem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable/up.PNG"))); // NOI18N
        ChangeElem.setBorderPainted(false);
        ChangeElem.setContentAreaFilled(false);
        ChangeElem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeElemActionPerformed(evt);
            }
        });
        getContentPane().add(ChangeElem);
        ChangeElem.setBounds(480, 160, 40, 40);

        Edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable/media_list.png"))); // NOI18N
        Edit.setBorderPainted(false);
        Edit.setContentAreaFilled(false);
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });
        getContentPane().add(Edit);
        Edit.setBounds(530, 130, 30, 30);
        getContentPane().add(Types);
        Types.setBounds(270, 170, 210, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        closeForm();
    }//GEN-LAST:event_formWindowClosing

    private void SizeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SizeKeyPressed
        onKeyPressed("size", Size, evt, new I_WizardAction() {
            @Override
            public void onAction(int value) {
                array.setSize(value);
            }
        });
    }//GEN-LAST:event_SizeKeyPressed

    private void DXYKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DXYKeyPressed
        onKeyPressed("dXY", DXY, evt, new I_WizardAction() {
            @Override
            public void onAction(int value) {
                array.setDxy(value);
            }
        });
    }//GEN-LAST:event_DXYKeyPressed

    private void ChangeElemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeElemActionPerformed
        new OK(300, 300, "Изменить тип элемента масива", new I_Button() {
            @Override
            public void onPush() {
                try {
                    int type = types.get(Types.getSelectedIndex()).value();
                    Meta2GUI entity = (Meta2GUI) createByType(type);
                    if (entity.getErrors().getErrCount()!=0){
                        System.out.println(entity.getErrors().toString());
                        main.popup("Ошибка создания элемента ЧМИ");
                        return;
                        }
                    array.setElem(entity);
                    Elem.setText(entity.getFullTitle());
                    back.onEnter("Изменен тип элемента массива на "+types.get(Types.getSelectedIndex()).title());
                    } catch (Exception ee){
                        System.out.println("Ошибка: "+ee.toString());
                        array.setElem(null);
                }
            }
        });
    }//GEN-LAST:event_ChangeElemActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        if (array.getElem()==null)
            return;
        openWizardByType(array.getElem());
    }//GEN-LAST:event_EditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChangeElem;
    private javax.swing.JTextField DXY;
    private javax.swing.JButton Edit;
    private javax.swing.JTextField Elem;
    private javax.swing.JTextField Size;
    private java.awt.Choice Types;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
