/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package romanow.abc.desktop.wizard;

import romanow.abc.desktop.ESSMetaPanel;
import romanow.abc.desktop.MainBaseFrame;
import romanow.abc.core.entity.subject2area.ESS2Entity;

import javax.swing.*;
import java.awt.*;
import java.awt.event.KeyEvent;

/**
 *
 * @author romanow0
 */
public class WizardBaseViewDB extends javax.swing.JFrame {
    protected MainBaseFrame main;
    protected ESSMetaPanel panel;
    public I_Wizard back;
    protected ESS2Entity entity;
    protected int changeCount=0;
    public void oneUpdate(String ss){
        changeCount++;
        SaveChanges.setVisible(true);
        ChangesCount.setVisible(true);
        ChangesCount.setText(""+changeCount);
        if (back!=null)
            back.onEnter(ss);
        }
    public WizardBaseViewDB(ESSMetaPanel frame0, ESS2Entity entity0, I_Wizard back0) {
        initComponents();
        entity = entity0;
        back = back0;
        panel = frame0;
        main = panel.getFrame();
        setVisible(true);
        setLocation(200,250);
        setTitle(entity.getTitle());
        Title.setText(entity.getTitle());
        Comment.setText(entity.getComment());
        ShortName.setText(entity.getShortName());
        SaveChanges.setVisible(false);
        ChangesCount.setVisible(false);
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        ShortName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Comment = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Title = new javax.swing.JTextField();
        SaveChanges = new javax.swing.JButton();
        ChangesCount = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        ShortName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ShortNameKeyPressed(evt);
            }
        });
        getContentPane().add(ShortName);
        ShortName.setBounds(60, 10, 80, 25);

        jLabel1.setText("Название");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 15, 70, 14);

        Comment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CommentKeyPressed(evt);
            }
        });
        getContentPane().add(Comment);
        Comment.setBounds(100, 50, 530, 25);

        jLabel2.setText("Комментарий");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 55, 100, 14);

        jLabel3.setText("Имя ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 15, 40, 14);

        Title.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TitleKeyPressed(evt);
            }
        });
        getContentPane().add(Title);
        Title.setBounds(230, 10, 400, 25);

        SaveChanges.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable/save.png"))); // NOI18N
        SaveChanges.setBorderPainted(false);
        SaveChanges.setContentAreaFilled(false);
        SaveChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveChangesActionPerformed(evt);
            }
        });
        getContentPane().add(SaveChanges);
        SaveChanges.setBounds(640, 10, 30, 30);

        ChangesCount.setEnabled(false);
        getContentPane().add(ChangesCount);
        ChangesCount.setBounds(640, 50, 40, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void closeForm(){
        dispose();
        }

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        closeForm();
    }//GEN-LAST:event_formWindowClosing

    private void ShortNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ShortNameKeyPressed
        onStringKeyPressed("shortName", ShortName, evt, new I_WizardActionString() {
            @Override
            public void onAction(String value) {
                entity.setShortName(value);
            }
        });
    }//GEN-LAST:event_ShortNameKeyPressed

    private void TitleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TitleKeyPressed
        onStringKeyPressed("title", Title, evt, new I_WizardActionString() {
            @Override
            public void onAction(String value) {
                entity.setTitle(value);
            }
        });
    }//GEN-LAST:event_TitleKeyPressed

    private void CommentKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CommentKeyPressed
        onStringKeyPressed("comment", Comment, evt, new I_WizardActionString() {
            @Override
            public void onAction(String value) {
                entity.setComment(value);
            }
        });
    }//GEN-LAST:event_CommentKeyPressed

    private void SaveChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveChangesActionPerformed
        if (back!=null)
            back.onUpdate();
        closeForm();
    }//GEN-LAST:event_SaveChangesActionPerformed


    public void onKeyPressed(String name, JTextField fld, KeyEvent evt, I_WizardAction action){
        if(evt.getKeyCode()!=10) return;
        int xx=0;
        try {
            xx = Integer.parseInt(fld.getText());
            action.onAction(xx);
            if (evt!=null)
                main.viewUpdate(evt,true);
            oneUpdate("Изменено "+name+": "+fld.getText());
        } catch (Exception ee){
            System.out.println("Ошибка целого: "+fld.getText());
            if (evt!=null)
                main.viewUpdate(evt,false);
        }
    }
    public void onKeyPressed(String name, JCheckBox hex, TextField fld, KeyEvent evt, I_WizardAction action){
        if(evt.getKeyCode()!=10) return;
        int xx=0;
        String ss = fld.getText();
        try {
            if (!hex.isSelected())
                xx = Integer.parseInt(ss);
            else{
                xx = Integer.parseInt(ss.startsWith("0x") ? ss.substring(2) : ss,16);
            }
            action.onAction(xx);
            if (evt!=null)
                main.viewUpdate(evt,true);
            back.onEnter("Изменено "+name+": "+fld.getText());
            } catch (Exception ee){
                System.out.println("Ошибка целого: "+fld.getText());
                if (evt!=null)
                main.viewUpdate(evt,false);
                }
        }
    public void onColorKeyPressed(String name,JTextField fld, JButton button, KeyEvent evt, I_WizardAction action){
        if(evt.getKeyCode()!=10) return;
        long xx=0;
        try {
            xx = Long.parseLong(fld.getText(),16);
            action.onAction((int)xx);
            if (evt!=null)
                main.viewUpdate(evt,true);
            button.setBackground(new Color((int)xx));
            oneUpdate("Изменено "+name+": "+fld.getText());
        } catch (Exception ee){
            System.out.println("Ошибка целого(16): "+fld.getText());
            if (evt!=null)
                main.viewUpdate(evt,false);
        }
    }
    public void onStringKeyPressed(String name,JTextField fld, KeyEvent evt, I_WizardActionString action){
        if(evt.getKeyCode()!=10) return;
        action.onAction(fld.getText());
        if (evt!=null)
            main.viewUpdate(evt,true);
        oneUpdate("Изменено "+name+": "+fld.getText());
    }
    public void onKey16Pressed(String name,JTextField fld, KeyEvent evt, I_WizardAction action){
        if(evt.getKeyCode()!=10) return;
        long xx=0;
        try {
            xx = Long.parseLong(fld.getText(),16);
            action.onAction((int)xx);
            if (evt!=null)
                main.viewUpdate(evt,true);
            oneUpdate("Изменено "+name+": "+fld.getText());
        } catch (Exception ee){
            System.out.println("Ошибка целого(16): "+fld.getText());
            if (evt!=null)
                main.viewUpdate(evt,false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ChangesCount;
    private javax.swing.JTextField Comment;
    private javax.swing.JButton SaveChanges;
    private javax.swing.JTextField ShortName;
    private javax.swing.JTextField Title;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
