/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package romanow.abc.desktop.wizard;


import romanow.abc.core.entity.metadata.Meta2Entity;
import romanow.abc.core.entity.metadata.view.Meta2GUIEnvVar;
import romanow.abc.core.entity.metadata.view.Meta2GUIScript;

/**
 *
 * @author romanow0
 */
public class WizardMeta2GUIEnvVar extends WizardMeta2GUI {
    private Meta2GUIEnvVar envVar;
    public WizardMeta2GUIEnvVar() {
        initComponents();
        }
    public void openForm(WizardBaseView parentView0, Meta2Entity entity0){
        super.openForm(parentView0,entity0);
        setSize(750,200);
        envVar = (Meta2GUIEnvVar)  entity;
        ScriptName.setText(envVar.getEnvVarName());
        W2.setText(""+envVar.getW2());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        ScriptName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        W2 = new javax.swing.JTextField();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setText("Скрипт ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 135, 70, 14);

        ScriptName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ScriptNameKeyPressed(evt);
            }
        });
        getContentPane().add(ScriptName);
        ScriptName.setBounds(70, 130, 120, 25);

        jLabel2.setText("W2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(200, 135, 30, 14);

        W2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                W2KeyPressed(evt);
            }
        });
        getContentPane().add(W2);
        W2.setBounds(230, 130, 50, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        closeForm();
    }//GEN-LAST:event_formWindowClosing

    private void ScriptNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ScriptNameKeyPressed
        onStringKeyPressed("envVarName", ScriptName, evt, new I_WizardActionString() {
            @Override
            public void onAction(String value) {
                envVar.setEnvVarName(value);
            }
        });
    }//GEN-LAST:event_ScriptNameKeyPressed

    private void W2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_W2KeyPressed
        onKeyPressed("W2", W2, evt, new I_WizardAction() {
            @Override
            public void onAction(int value) {
                envVar.setW2(value);
            }
        });
    }//GEN-LAST:event_W2KeyPressed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ScriptName;
    private javax.swing.JTextField W2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
