/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package romanow.abc.desktop.wizard;

import java.awt.*;

/**
 *
 * @author romanow0
 */
public class WizardMetaEntitySelector extends javax.swing.JPanel {

    /**
     * Creates new form Meta2EntitySelector
     */
    private int type;
    private I_WizardEntitySelector back;
    public WizardMetaEntitySelector(String name, int type0, I_WizardEntitySelector back0) {
        initComponents();
        back = back0;
        type = type0;
        Label.setText(name);
        List.setVisible(true);
        }
    public Choice getList(){ return  List; }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        List = new java.awt.Choice();
        Edit = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        Remove = new javax.swing.JButton();
        Label = new javax.swing.JLabel();

        setLayout(null);

        List.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ListItemStateChanged(evt);
            }
        });
        add(List);
        List.setBounds(140, 10, 480, 20);

        Edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable/media_list.png"))); // NOI18N
        Edit.setBorderPainted(false);
        Edit.setContentAreaFilled(false);
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });
        add(Edit);
        Edit.setBounds(630, 10, 30, 30);

        Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable/add.png"))); // NOI18N
        Add.setBorderPainted(false);
        Add.setContentAreaFilled(false);
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        add(Add);
        Add.setBounds(670, 10, 40, 30);

        Remove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable/remove.png"))); // NOI18N
        Remove.setBorderPainted(false);
        Remove.setContentAreaFilled(false);
        Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveActionPerformed(evt);
            }
        });
        add(Remove);
        Remove.setBounds(710, 10, 30, 30);

        Label.setText("Источники данных");
        add(Label);
        Label.setBounds(10, 10, 120, 14);
    }// </editor-fold>//GEN-END:initComponents

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        if (List.getItemCount()!=0)
            back.onEdit(type,List.getSelectedIndex());
    }//GEN-LAST:event_EditActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        back.onAdd(type);
    }//GEN-LAST:event_AddActionPerformed

    private void RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveActionPerformed
        if (List.getItemCount()!=0)
            back.onRemove(type,List.getSelectedIndex());
    }//GEN-LAST:event_RemoveActionPerformed

    private void ListItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ListItemStateChanged
        if (List.getItemCount()!=0)
            back.onSelect(type,List.getSelectedIndex());
    }//GEN-LAST:event_ListItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Edit;
    private javax.swing.JLabel Label;
    private java.awt.Choice List;
    private javax.swing.JButton Remove;
    // End of variables declaration//GEN-END:variables
}
