/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package romanow.abc.desktop.wizard;


import okhttp3.MultipartBody;
import retrofit2.Call;
import romanow.abc.core.API.RestAPICommon;
import romanow.abc.core.constants.Values;
import romanow.abc.core.entity.artifacts.Artifact;
import romanow.abc.core.entity.artifacts.ArtifactList;
import romanow.abc.core.entity.metadata.Meta2Entity;
import romanow.abc.core.entity.metadata.view.Meta2GUIImageScriptLevel;
import romanow.abc.core.entity.metadata.view.Meta2GUIScript;
import romanow.abc.core.utils.FileNameExt;
import romanow.abc.desktop.APICall;

import java.awt.*;

/**
 *
 * @author romanow0
 */
public class WizardMeta2GUIImageScriptLevel extends WizardMeta2GUI {
    private Meta2GUIImageScriptLevel elem;
    private ArtifactList artifacts = new ArtifactList();
    public WizardMeta2GUIImageScriptLevel() {
        initComponents();
        }
    public void openForm(WizardBaseView parentView0, Meta2Entity entity0){
        super.openForm(parentView0,entity0);
        resizeHight(300);
        elem = (Meta2GUIImageScriptLevel)  entity;
        ScriptName.setText(elem.getScripName());
        NoCalc.setSelected(elem.isNoCalc());
        Alpha.setText(""+elem.getAlphaProc());
        ColorBack.setText(String.format("%x",elem.getColorBack()));
        ColorLevel.setText(String.format("%x",elem.getColorLevel()));
        ColorBackButton.setBackground(new Color(elem.getColorBack()));
        ColorLevelButton.setBackground(new Color(elem.getColorLevel()));
        LowLevel.setText(""+elem.getLowLevel());
        HighLevel.setText(""+elem.getHighLevel());
        ImageH.setText(""+elem.getImageH());
        ImageW.setText(""+elem.getImageW());
        refreshImageList();
        selectCurrentImage();
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        ScriptName = new javax.swing.JTextField();
        NoCalc = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        ImageH = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        ImageW = new javax.swing.JTextField();
        ImageList = new java.awt.Choice();
        SetImage = new javax.swing.JButton();
        UploadImage = new javax.swing.JButton();
        ImageAlias = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Alpha = new javax.swing.JTextField();
        ColorBackButton = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        ColorLevel = new javax.swing.JTextField();
        ColorLevelButton = new javax.swing.JButton();
        HighLevel = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        ColorBack = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        LowLevel = new javax.swing.JTextField();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setText("Скрипт ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 130, 70, 14);

        ScriptName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ScriptNameKeyPressed(evt);
            }
        });
        getContentPane().add(ScriptName);
        ScriptName.setBounds(20, 150, 120, 25);

        NoCalc.setText("Не вычислять");
        NoCalc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                NoCalcItemStateChanged(evt);
            }
        });
        getContentPane().add(NoCalc);
        NoCalc.setBounds(70, 125, 110, 23);

        jLabel11.setText("H image");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 180, 50, 14);

        ImageH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ImageHKeyPressed(evt);
            }
        });
        getContentPane().add(ImageH);
        ImageH.setBounds(20, 200, 50, 25);

        jLabel14.setText("Alias");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(500, 180, 80, 14);

        ImageW.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ImageWKeyPressed(evt);
            }
        });
        getContentPane().add(ImageW);
        ImageW.setBounds(80, 200, 50, 25);
        getContentPane().add(ImageList);
        ImageList.setBounds(150, 200, 270, 20);

        SetImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable/save.png"))); // NOI18N
        SetImage.setBorderPainted(false);
        SetImage.setContentAreaFilled(false);
        SetImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetImageActionPerformed(evt);
            }
        });
        getContentPane().add(SetImage);
        SetImage.setBounds(430, 190, 30, 30);

        UploadImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable/upload.png"))); // NOI18N
        UploadImage.setBorderPainted(false);
        UploadImage.setContentAreaFilled(false);
        UploadImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadImageActionPerformed(evt);
            }
        });
        getContentPane().add(UploadImage);
        UploadImage.setBounds(590, 190, 30, 30);
        getContentPane().add(ImageAlias);
        ImageAlias.setBounds(470, 200, 110, 25);

        jLabel15.setText("W image");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(80, 180, 60, 14);

        jLabel12.setText("Прозрачн.");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(180, 130, 60, 14);

        Alpha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AlphaKeyPressed(evt);
            }
        });
        getContentPane().add(Alpha);
        Alpha.setBounds(180, 150, 40, 25);
        getContentPane().add(ColorBackButton);
        ColorBackButton.setBounds(330, 150, 30, 30);

        jLabel16.setText("Цвет уровня");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(380, 130, 100, 14);

        ColorLevel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ColorLevelKeyPressed(evt);
            }
        });
        getContentPane().add(ColorLevel);
        ColorLevel.setBounds(370, 150, 80, 25);
        getContentPane().add(ColorLevelButton);
        ColorLevelButton.setBounds(460, 150, 30, 30);

        HighLevel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                HighLevelKeyPressed(evt);
            }
        });
        getContentPane().add(HighLevel);
        HighLevel.setBounds(570, 150, 60, 25);

        jLabel13.setText("Уровни 0...100%");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(510, 130, 100, 14);

        ColorBack.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ColorBackKeyPressed(evt);
            }
        });
        getContentPane().add(ColorBack);
        ColorBack.setBounds(240, 150, 80, 25);

        jLabel17.setText("Цвет фона");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(260, 130, 80, 14);

        LowLevel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LowLevelKeyPressed(evt);
            }
        });
        getContentPane().add(LowLevel);
        LowLevel.setBounds(500, 150, 60, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        closeForm();
    }//GEN-LAST:event_formWindowClosing

    private void ScriptNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ScriptNameKeyPressed
        onStringKeyPressed("scriptName", ScriptName, evt, new I_WizardActionString() {
            @Override
            public void onAction(String value) {
                elem.setScripName(value);
                }
            });
    }//GEN-LAST:event_ScriptNameKeyPressed

    private void NoCalcItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_NoCalcItemStateChanged
        elem.setNoCalc(NoCalc.isSelected());
        back.onEnter("Изменено noCalc"+": "+elem.isNoCalc());
    }//GEN-LAST:event_NoCalcItemStateChanged

    private void ImageHKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ImageHKeyPressed
        onKeyPressed("imageH", ImageH, evt, new I_WizardAction() {
            @Override
            public void onAction(int value) {
                elem.setImageH(value);
            }
        });
    }//GEN-LAST:event_ImageHKeyPressed

    private void ImageWKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ImageWKeyPressed
        onKeyPressed("imageW", ImageW, evt, new I_WizardAction() {
            @Override
            public void onAction(int value) {
                elem.setImageW(value);
            }
        });
    }//GEN-LAST:event_ImageWKeyPressed

    private void SetImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetImageActionPerformed
        if (artifacts.size()==0)
        return;
        int idx = ImageList.getSelectedIndex();
        Artifact art = idx==0 ? new Artifact() : artifacts.get(idx-1);
        elem.getPicture().setOidRef(art);
        back.onEnter("Выбрана картинка "+art.getTitle());
    }//GEN-LAST:event_SetImageActionPerformed

    private void UploadImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadImageActionPerformed
        FileNameExt fname = main.getInputFileName("Импорт картинок 2.0", "*.*", null);
        final MultipartBody.Part body = RestAPICommon.createMultipartBody(fname);
        new APICall<Artifact>(main) {
            @Override
            public Call<Artifact> apiFun() {
                return main.getService().upload(main.getDebugToken(), Values.ESSImageFileDescription+" "+ImageAlias.getText(), fname.fileName(), body);
                }
            @Override
            public void onSucess(final Artifact art) {
                elem.getPicture().setOidRef(art);
                back.onEnter("Выбрана картинка "+art.getTitle());
                refreshImageList();
                }
            };
    }//GEN-LAST:event_UploadImageActionPerformed

    private void AlphaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AlphaKeyPressed
        onKeyPressed("alphaProc", Alpha, evt, new I_WizardAction() {
            @Override
            public void onAction(int value) {
                elem.setAlphaProc(value);
            }
        });
    }//GEN-LAST:event_AlphaKeyPressed

    private void ColorLevelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ColorLevelKeyPressed
        onColorKeyPressed("colorLevel", ColorLevel, ColorLevelButton, evt, new I_WizardAction() {
            @Override
            public void onAction(int value) {
                elem.setColorLevel(value);
            }
        });
    }//GEN-LAST:event_ColorLevelKeyPressed

    private void HighLevelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HighLevelKeyPressed
        onKeyPressed("highLevel", HighLevel, evt, new I_WizardAction() {
            @Override
            public void onAction(int value) {
                elem.setHighLevel(value);
                }
            });
        }//GEN-LAST:event_HighLevelKeyPressed

    private void ColorBackKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ColorBackKeyPressed
        onColorKeyPressed("colorBack", ColorBack, ColorBackButton, evt, new I_WizardAction() {
            @Override
            public void onAction(int value) {
                elem.setColorBack(value);
            }
        });

    }//GEN-LAST:event_ColorBackKeyPressed

    private void LowLevelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LowLevelKeyPressed
        onKeyPressed("lowLevel", LowLevel, evt, new I_WizardAction() {
            @Override
            public void onAction(int value) {
                elem.setLowLevel(value);
            }
        });

    }//GEN-LAST:event_LowLevelKeyPressed

    private void selectCurrentImage(){
        long ownOid = elem.getPicture().getOid();
        if (ownOid==0){
            ImageList.select(0);
            return;
        }
        int idx2=1;
        for(Artifact artifact : artifacts){
            if (artifact.getOid()==ownOid){
                ImageList.select(idx2);
                break;
                }
            idx2++;
            }
        }
    private void refreshImageList(){
        new APICall<ArtifactList>(main) {
            @Override
            public Call<ArtifactList> apiFun() {
                return main.getService().getArtifactConditionList(main.getDebugToken(), Values.ArtifactImageType,"",
                        Values.ESSImageFileDescription,"",0,0,0,0);
                }
            @Override
            public void onSucess(ArtifactList oo) {
                artifacts = oo;
                ImageList.removeAll();
                artifacts.sortById();
                ImageList.add("...");
                for(Artifact ctr : artifacts)
                    ImageList.add(ctr.getTitle());
                }
            };
        }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Alpha;
    private javax.swing.JTextField ColorBack;
    private javax.swing.JButton ColorBackButton;
    private javax.swing.JTextField ColorLevel;
    private javax.swing.JButton ColorLevelButton;
    private javax.swing.JTextField HighLevel;
    private javax.swing.JTextField ImageAlias;
    private javax.swing.JTextField ImageH;
    private java.awt.Choice ImageList;
    private javax.swing.JTextField ImageW;
    private javax.swing.JTextField LowLevel;
    private javax.swing.JCheckBox NoCalc;
    private javax.swing.JTextField ScriptName;
    private javax.swing.JButton SetImage;
    private javax.swing.JButton UploadImage;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    // End of variables declaration//GEN-END:variables
}
