/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package romanow.abc.desktop.wizard;

import java.util.ArrayList;

import com.google.gson.Gson;
import okhttp3.MultipartBody;
import retrofit2.Call;
import romanow.abc.core.API.RestAPICommon;
import romanow.abc.core.DBRequest;
import romanow.abc.core.OidString;
import romanow.abc.core.constants.Values;
import romanow.abc.core.entity.artifacts.Artifact;
import romanow.abc.core.entity.baseentityes.JEmpty;
import romanow.abc.core.entity.subject2area.ESS2Entity;
import romanow.abc.core.entity.subject2area.ESS2Equipment;
import romanow.abc.core.entity.subject2area.ESS2MetaFile;
import romanow.abc.core.entity.subject2area.ESS2Node;
import romanow.abc.core.utils.FileNameExt;
import romanow.abc.desktop.APICall;
import static romanow.abc.desktop.BasePanel.EventLogToFront;
import romanow.abc.desktop.ESSMetaPanel;

/**
 *
 * @author romanow0
 */
public class WizardESS2Equipment extends WizardBaseViewDB {

    private ESS2Node node;
    private ESS2Equipment equipment;
    private boolean onStart=false;
    private void selectChoice(){
        if (equipment.getMetaFile().getOid()==0){
            MetaFile.select(0);
            return;
            }
        long oid = equipment.getMetaFile().getRef().getOid();
        for(int i=0;i<panel.getMetaData().size();i++){
            if (panel.getMetaData().get(i).getOid()==oid){
                MetaFile.select(i+1);
                return;
                }
            MetaFile.select(0);
            }
        }
    public WizardESS2Equipment(ESSMetaPanel frame0, ESS2Entity entity0, I_Wizard back0) {
        super("Оборудование",frame0,entity0,back0);
        initComponents();
        setSize(750,220);
        resizeHeight(220);
        onStart = true;
        equipment = (ESS2Equipment)entity0;
        if (equipment.getReports61850().getOid()!=0){
            Reports61850.setText(equipment.getReports61850().getRef().getOriginalName());
            }
        MultiUnit.setSelected(equipment.isMultiUnit());
        IEC61850LNType.setText(equipment.getIec61850LNType());
        MetaFile.removeAll();
        MetaFile.add("...");
        for(ESS2MetaFile metaFile : panel.getMetaData())
            MetaFile.add(metaFile.toString());
        selectChoice();
        onStart = false;
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        MetaFile = new java.awt.Choice();
        SetMetaFile = new javax.swing.JButton();
        MultiUnit = new javax.swing.JCheckBox();
        Reports61850 = new javax.swing.JTextField();
        DownLoadReports61850 = new javax.swing.JButton();
        UploadReports61851 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        IEC61850LNType = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(10, 120, 460, 3);
        getContentPane().add(MetaFile);
        MetaFile.setBounds(10, 90, 400, 20);

        SetMetaFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable/save.png"))); // NOI18N
        SetMetaFile.setBorderPainted(false);
        SetMetaFile.setContentAreaFilled(false);
        SetMetaFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetMetaFileActionPerformed(evt);
            }
        });
        getContentPane().add(SetMetaFile);
        SetMetaFile.setBounds(420, 80, 30, 30);

        MultiUnit.setText("Мульти-Unit");
        MultiUnit.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                MultiUnitItemStateChanged(evt);
            }
        });
        getContentPane().add(MultiUnit);
        MultiUnit.setBounds(10, 130, 120, 20);

        Reports61850.setEnabled(false);
        getContentPane().add(Reports61850);
        Reports61850.setBounds(160, 130, 220, 25);

        DownLoadReports61850.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable/download.png"))); // NOI18N
        DownLoadReports61850.setBorderPainted(false);
        DownLoadReports61850.setContentAreaFilled(false);
        DownLoadReports61850.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownLoadReports61850ActionPerformed(evt);
            }
        });
        getContentPane().add(DownLoadReports61850);
        DownLoadReports61850.setBounds(420, 130, 30, 30);

        UploadReports61851.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable/upload.png"))); // NOI18N
        UploadReports61851.setBorderPainted(false);
        UploadReports61851.setContentAreaFilled(false);
        UploadReports61851.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadReports61851ActionPerformed(evt);
            }
        });
        getContentPane().add(UploadReports61851);
        UploadReports61851.setBounds(390, 130, 30, 30);

        jLabel1.setText("61850");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(460, 145, 60, 16);

        jLabel2.setText("LNType");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(460, 130, 60, 16);

        jLabel3.setText("Отчеты");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 130, 60, 16);

        IEC61850LNType.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                IEC61850LNTypeKeyPressed(evt);
            }
        });
        getContentPane().add(IEC61850LNType);
        IEC61850LNType.setBounds(510, 130, 80, 25);

        jLabel4.setText("61850");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 145, 60, 16);

        jLabel5.setText("Отчеты");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(110, 130, 60, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SetMetaFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetMetaFileActionPerformed
        if (MetaFile.getSelectedIndex()==0){
            main.popup("Не выбран мета-файл");
            return;
            }
        ESS2MetaFile metaFile = panel.getMetaData().get(MetaFile.getSelectedIndex()-1);
        if (!Values.isEquipmentType(metaFile.getMetaType())) {
            main.popup("Недопустимый тип для мета-файла оборудования");
            return;
            }
        equipment.getMetaFile().setOid(metaFile.getOid());
        oneUpdate("Изменено metaFile: "+metaFile.toString());
    }//GEN-LAST:event_SetMetaFileActionPerformed

    private void MultiUnitItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_MultiUnitItemStateChanged
        if (onStart)
            return;
        equipment.setMultiUnit(MultiUnit.isSelected());
        oneUpdate("Изменено multiUnit: "+MultiUnit.isSelected());
    }//GEN-LAST:event_MultiUnitItemStateChanged

    private void DownLoadReports61850ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DownLoadReports61850ActionPerformed
        if (equipment.getReports61850().getOid()!=0)
            main.loadFile(equipment.getReports61850().getRef());
    }//GEN-LAST:event_DownLoadReports61850ActionPerformed


    private void uploadReports61870(){
        FileNameExt fname = main.getInputFileName("Импорт описания отчетов и DataSet для 61850", "*.xml", null);
        final MultipartBody.Part body = RestAPICommon.createMultipartBody(fname);
        new APICall<Artifact>(main) {
            @Override
            public Call<Artifact> apiFun() {
                return main.getService().upload(main.getDebugToken(), "Meta-Data import", fname.fileName(), body);
                }
            @Override
            public void onSucess(final Artifact oo) {
                equipment.getReports61850().setOidRef(oo);
                new APICall<JEmpty>(main) {
                    @Override
                    public Call<JEmpty> apiFun() {
                        return main.getService().updateEntityField(main.getDebugToken(),"reports61850", new DBRequest(equipment, new Gson()));
                        }
                    @Override
                    public void onSucess(JEmpty oo) {
                        Reports61850.setText(equipment.getReports61850().getRef().getOriginalName());
                        main.popup("Импорт описания отчетов");
                        }
                    };
                }
            };
        }

    private void UploadReports61851ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadReports61851ActionPerformed
        if (equipment.getReports61850().getOid()!=0){
            new APICall<JEmpty>(main) {
                @Override
                public Call<JEmpty> apiFun() {
                    return main.getService().removeArtifact(main.getDebugToken(), equipment.getReports61850().getOid());
                    }
                @Override
                public void onSucess(JEmpty oo) {
                    uploadReports61870();
                    }
                };
            }
        else
            uploadReports61870();
    }//GEN-LAST:event_UploadReports61851ActionPerformed

    private void IEC61850LNTypeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IEC61850LNTypeKeyPressed
        onStringKeyPressed("iec61850LNType", IEC61850LNType, evt, new I_WizardActionString() {
            @Override
            public void onAction(String value) {
                equipment.setIec61850LNType(value);
            }
        });
    }//GEN-LAST:event_IEC61850LNTypeKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WizardESS2Equipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WizardESS2Equipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WizardESS2Equipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WizardESS2Equipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new WizardESS2Connector().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DownLoadReports61850;
    private javax.swing.JTextField IEC61850LNType;
    private java.awt.Choice MetaFile;
    private javax.swing.JCheckBox MultiUnit;
    private javax.swing.JTextField Reports61850;
    private javax.swing.JButton SetMetaFile;
    private javax.swing.JButton UploadReports61851;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
