/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package romanow.abc.desktop.wizard;

import lombok.Getter;
import romanow.abc.core.UniException;
import romanow.abc.core.constants.Values;
import romanow.abc.core.entity.metadata.*;
import romanow.abc.desktop.I_Button;
import romanow.abc.desktop.OK;

import java.awt.*;

/**
 *
 * @author romanow0
 */
public class WizardMeta2GUIView extends WizardBaseView {

    /**
     * Creates new form WizardMeta2Equipment
     */
    public WizardMeta2GUIView() {
        initComponents();
        setBounds(200,200,800,250);
        }
   private Meta2GUIView view;
   @Getter private Meta2EntityList<Meta2GUIForm> list;
   private WizardMetaEntitySelector selector;
   @Override
   public void openForm(WizardBaseView parentView0, Meta2Entity entity0){
       super.openForm(parentView0,entity0);
       resizeHeight(300);
       view = (Meta2GUIView) entity0;
       BackColor.setText(""+String.format("%06x",view.getBackColor()));
       BackColorButton.setBackground(new Color(view.getBackColor()));
       TextColor.setText(""+String.format("%06x",view.getTextColor()));
       TextColorButton.setBackground(new Color(view.getTextColor()));
       ElemColor.setText(""+String.format("%06x",view.getCommonBackColor()));
       ElemColorButton.setBackground(new Color(view.getCommonBackColor()));
       MenuModes.setText(""+view.getMenuModes());
       Height.setText(""+view.getHeight());
       Width.setText(""+view.getWidth());
       //---------------------------------------------------------------------------
       MenuOnColor.setText(""+String.format("%06x",view.getMenuButtonOnColor()));
       MenuOnColorButton.setBackground(new Color(view.getMenuButtonOnColor()));
       MenuOffColor.setText(""+String.format("%06x",view.getMenuButtonOffColor()));
       MenuOffColorButton.setBackground(new Color(view.getMenuButtonOffColor()));
       MenuTextColor.setText(""+String.format("%06x",view.getMenuButtonTextColor()));
       MenuTextColorButton.setBackground(new Color(view.getMenuButtonTextColor()));
       MenuBold.setSelected(view.isMenuFontBold());
       MenuFontSize.setText(""+view.getMenuButtonFontSize());
       MenuButtonW.setText(""+view.getMenuButtonW());
       MenuButtonH.setText(""+view.getMenuButtonH());
       //-------------------------------------------------------------------------
       list = view.getForms();
       selector = new WizardMetaEntitySelector("Формы", Values.MEGUIForm,callBack);
       selector.setBounds(10,80,750,40);
       getContentPane().add(selector);
       refreshList();
       }
    public void refreshList(){
            Choice choice = selector.getList();
            choice.removeAll();
            for(Meta2GUIForm form : list.getList())
                choice.add(form.getFullTitle());
            }
    private I_WizardEntitySelector callBack = new I_WizardEntitySelector() {
        @Override
        public void onEdit(int type, int idx) {
            String ss = openWizardByType(list.get(idx));
            if (ss!=null)
                System.out.println(ss);
        }
        @Override
        public void onRemove(int type, int idx) {
            final String title = list.get(idx).getTitle();
            new OK(300, 300, "Удалить " + title, new I_Button() {
                @Override
                public void onPush() {
                    list.getList().remove(idx);
                    refreshList();
                    back.onEnter("Удален: "+title);
                }
            });
        }
        @Override
        public void onAdd(int type) {
            try {
                Meta2GUIForm entity = (Meta2GUIForm) Values.createEntityByType("MetaElem",type,"romanow.abc.core.entity.metadata");
                list.add(entity);
                refreshList();
                String ss = openWizardByType(entity);
                if (ss!=null)
                    System.out.println(ss);
            } catch (UniException e) {
                System.out.println(e.toString());
            }
        }
        @Override
        public void onSelect(int type, int idx) {}
        };


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        BackColor = new javax.swing.JTextField();
        BackColorButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        MenuOnColor = new javax.swing.JTextField();
        MenuOnColorButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        MenuOffColor = new javax.swing.JTextField();
        MenuOffColorButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        TextColor = new javax.swing.JTextField();
        TextColorButton = new javax.swing.JButton();
        ElemColor = new javax.swing.JTextField();
        ElemColorButton = new javax.swing.JButton();
        Height = new javax.swing.JTextField();
        Width = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        MenuModes = new javax.swing.JTextField();
        MenuTextColor = new javax.swing.JTextField();
        MenuTextColorButton = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        MenuBold = new javax.swing.JCheckBox();
        jLabel20 = new javax.swing.JLabel();
        MenuButtonW = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        MenuFontSize = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        MenuButtonH = new javax.swing.JTextField();

        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(10, 80, 750, 10);

        jLabel9.setText("Фон общий");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 150, 100, 16);

        BackColor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BackColorKeyPressed(evt);
            }
        });
        getContentPane().add(BackColor);
        BackColor.setBounds(110, 140, 60, 25);
        getContentPane().add(BackColorButton);
        BackColorButton.setBounds(170, 140, 25, 25);

        jLabel10.setText("Меню+");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(370, 150, 50, 16);

        MenuOnColor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MenuOnColorKeyPressed(evt);
            }
        });
        getContentPane().add(MenuOnColor);
        MenuOnColor.setBounds(420, 140, 60, 25);
        getContentPane().add(MenuOnColorButton);
        MenuOnColorButton.setBounds(480, 140, 25, 25);

        jLabel11.setText("Меню-");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(370, 175, 50, 16);

        MenuOffColor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MenuOffColorKeyPressed(evt);
            }
        });
        getContentPane().add(MenuOffColor);
        MenuOffColor.setBounds(420, 170, 60, 25);
        getContentPane().add(MenuOffColorButton);
        MenuOffColorButton.setBounds(480, 170, 25, 25);

        jLabel12.setText("Высота");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(210, 200, 50, 16);

        TextColor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextColorKeyPressed(evt);
            }
        });
        getContentPane().add(TextColor);
        TextColor.setBounds(270, 140, 60, 25);
        getContentPane().add(TextColorButton);
        TextColorButton.setBounds(330, 140, 25, 25);

        ElemColor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ElemColorKeyPressed(evt);
            }
        });
        getContentPane().add(ElemColor);
        ElemColor.setBounds(110, 170, 60, 25);
        getContentPane().add(ElemColorButton);
        ElemColorButton.setBounds(170, 170, 25, 25);

        Height.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                HeightKeyPressed(evt);
            }
        });
        getContentPane().add(Height);
        Height.setBounds(270, 200, 60, 25);

        Width.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                WidthKeyPressed(evt);
            }
        });
        getContentPane().add(Width);
        Width.setBounds(270, 170, 60, 25);

        jLabel15.setText("Ширина");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(520, 175, 50, 16);

        jLabel16.setText("Фон элементов");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(10, 175, 100, 16);

        jLabel17.setText("Расположение");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(340, 200, 100, 16);

        MenuModes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MenuModesKeyPressed(evt);
            }
        });
        getContentPane().add(MenuModes);
        MenuModes.setBounds(440, 200, 60, 25);

        MenuTextColor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MenuTextColorKeyPressed(evt);
            }
        });
        getContentPane().add(MenuTextColor);
        MenuTextColor.setBounds(570, 140, 60, 25);
        getContentPane().add(MenuTextColorButton);
        MenuTextColorButton.setBounds(630, 140, 25, 25);

        jLabel18.setText("Текст");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(210, 150, 50, 16);

        jLabel19.setText("Высота");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(520, 200, 50, 16);

        MenuBold.setText("Bold");
        MenuBold.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                MenuBoldItemStateChanged(evt);
            }
        });
        getContentPane().add(MenuBold);
        MenuBold.setBounds(620, 200, 60, 20);

        jLabel20.setText("Текст ");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(520, 150, 50, 16);

        MenuButtonW.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MenuButtonWKeyPressed(evt);
            }
        });
        getContentPane().add(MenuButtonW);
        MenuButtonW.setBounds(570, 170, 40, 25);

        jLabel21.setText("Шрифт");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(620, 175, 50, 16);

        MenuFontSize.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MenuFontSizeKeyPressed(evt);
            }
        });
        getContentPane().add(MenuFontSize);
        MenuFontSize.setBounds(670, 170, 40, 25);

        jLabel22.setText("меню");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(390, 215, 50, 16);

        jLabel23.setText("Ширина");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(210, 175, 50, 16);

        MenuButtonH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MenuButtonHKeyPressed(evt);
            }
        });
        getContentPane().add(MenuButtonH);
        MenuButtonH.setBounds(570, 200, 40, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackColorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BackColorKeyPressed
        onColorKeyPressed("backColor", BackColor, BackColorButton, evt, new I_WizardAction() {
            @Override
            public void onAction(int value) { view.setBackColor(value);
            }
        });
    }//GEN-LAST:event_BackColorKeyPressed

    private void MenuOnColorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MenuOnColorKeyPressed
        onColorKeyPressed("menuOnColor", MenuOnColor, MenuOnColorButton, evt, new I_WizardAction() {
            @Override
            public void onAction(int value) { view.setMenuButtonOnColor(value);
            }
        });
    }//GEN-LAST:event_MenuOnColorKeyPressed

    private void MenuOffColorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MenuOffColorKeyPressed
        onColorKeyPressed("menuOffColor", MenuOffColor, MenuOffColorButton, evt, new I_WizardAction() {
            @Override
            public void onAction(int value) { view.setMenuButtonOffColor(value);
            }
        });

    }//GEN-LAST:event_MenuOffColorKeyPressed

    private void TextColorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextColorKeyPressed
        onColorKeyPressed("textColor", TextColor, TextColorButton, evt, new I_WizardAction() {
            @Override
            public void onAction(int value) { view.setTextColor(value);
            }
        });

    }//GEN-LAST:event_TextColorKeyPressed

    private void ElemColorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ElemColorKeyPressed
        onColorKeyPressed("labelBackColor", ElemColor, ElemColorButton, evt, new I_WizardAction() {
            @Override
            public void onAction(int value) { view.setCommonBackColor(value);
            }
        });

    }//GEN-LAST:event_ElemColorKeyPressed

    private void WidthKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_WidthKeyPressed
        onKeyPressed("Width", Width, evt, new I_WizardAction() {
            @Override
            public void onAction(int value) {
                view.setWidth(value);
            }
        });
    }//GEN-LAST:event_WidthKeyPressed

    private void HeightKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HeightKeyPressed
        onKeyPressed("Height", Height, evt, new I_WizardAction() {
            @Override
            public void onAction(int value) {
                view.setHeight(value);
            }
        });

    }//GEN-LAST:event_HeightKeyPressed

    private void MenuModesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MenuModesKeyPressed
        onKeyPressed("MenuModes", MenuModes, evt, new I_WizardAction() {
            @Override
            public void onAction(int value) { view.setMenuModes(value);
            }
        });

    }//GEN-LAST:event_MenuModesKeyPressed

    private void MenuTextColorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MenuTextColorKeyPressed
        onColorKeyPressed("menuButtonTextColor", MenuTextColor, MenuTextColorButton, evt, new I_WizardAction() {
            @Override
            public void onAction(int value) { view.setMenuButtonTextColor(value);
            }
        });
    }//GEN-LAST:event_MenuTextColorKeyPressed

    private void MenuButtonWKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MenuButtonWKeyPressed
        onKeyPressed("MenuButtonW", MenuButtonW, evt, new I_WizardAction() {
            @Override
            public void onAction(int value) {
                view.setMenuButtonW(value);
            }
        });
    }//GEN-LAST:event_MenuButtonWKeyPressed

    private void MenuFontSizeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MenuFontSizeKeyPressed
        onKeyPressed("MenuButtonFontSize", MenuFontSize, evt, new I_WizardAction() {
            @Override
            public void onAction(int value) {
                view.setMenuButtonFontSize(value);
            }
        });
    }//GEN-LAST:event_MenuFontSizeKeyPressed

    private void MenuBoldItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_MenuBoldItemStateChanged
        if (busy)
            return;
        view.setMenuFontBold(MenuBold.isSelected());
        back.onEnter("Изменено MenuBold="+MenuBold.isSelected());
    }//GEN-LAST:event_MenuBoldItemStateChanged

    private void MenuButtonHKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MenuButtonHKeyPressed
        onKeyPressed("MenuButtonH", MenuButtonH, evt, new I_WizardAction() {
            @Override
            public void onAction(int value) {
                view.setMenuButtonH(value);
            }
        });
    }//GEN-LAST:event_MenuButtonHKeyPressed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BackColor;
    private javax.swing.JButton BackColorButton;
    private javax.swing.JTextField ElemColor;
    private javax.swing.JButton ElemColorButton;
    private javax.swing.JTextField Height;
    private javax.swing.JCheckBox MenuBold;
    private javax.swing.JTextField MenuButtonH;
    private javax.swing.JTextField MenuButtonW;
    private javax.swing.JTextField MenuFontSize;
    private javax.swing.JTextField MenuModes;
    private javax.swing.JTextField MenuOffColor;
    private javax.swing.JButton MenuOffColorButton;
    private javax.swing.JTextField MenuOnColor;
    private javax.swing.JButton MenuOnColorButton;
    private javax.swing.JTextField MenuTextColor;
    private javax.swing.JButton MenuTextColorButton;
    private javax.swing.JTextField TextColor;
    private javax.swing.JButton TextColorButton;
    private javax.swing.JTextField Width;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
