/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package romanow.abc.desktop.wizard;

import romanow.abc.core.entity.subject2area.ESS2Entity;
import romanow.abc.core.entity.subject2area.ESS2EquipEmulator;
import romanow.abc.core.entity.subject2area.ESS2Node;
import romanow.abc.desktop.ESSMetaPanel;
import romanow.abc.desktop.MainBaseFrame;

/**
 *
 * @author romanow0
 */
public class WizardESS2EquipEmulator extends WizardBaseViewDB {

    private ESS2EquipEmulator emulator;
    public WizardESS2EquipEmulator(ESSMetaPanel frame0, ESS2Entity entity0, I_Wizard back0) {
        super(frame0,entity0,back0);
        initComponents();
        emulator = (ESS2EquipEmulator) entity0;
        ClassName.setText(emulator.getClassName());
        Port.setText(""+emulator.getPort());
        Enabled.setSelected(emulator.isEnable());
        Trace.setSelected(emulator.isTrace());
        setSize(750,200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        Port = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ClassName = new javax.swing.JTextField();
        Enabled = new javax.swing.JCheckBox();
        Trace = new javax.swing.JCheckBox();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(10, 90, 460, 2);

        Port.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PortKeyPressed(evt);
            }
        });
        getContentPane().add(Port);
        Port.setBounds(330, 100, 80, 25);

        jLabel1.setText("Port");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(290, 105, 40, 14);

        jLabel2.setText("Класс (Java)");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 105, 80, 14);

        ClassName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ClassNameKeyPressed(evt);
            }
        });
        getContentPane().add(ClassName);
        ClassName.setBounds(100, 100, 180, 25);

        Enabled.setText("Включено");
        Enabled.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                EnabledItemStateChanged(evt);
            }
        });
        getContentPane().add(Enabled);
        Enabled.setBounds(420, 100, 77, 23);

        Trace.setText("Трассировка");
        Trace.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                TraceItemStateChanged(evt);
            }
        });
        getContentPane().add(Trace);
        Trace.setBounds(420, 120, 130, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PortKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PortKeyPressed
        onKeyPressed("Port", Port, evt, new I_WizardAction() {
            @Override
            public void onAction(int value) {
                emulator.setPort(value);
                }
            });
    }//GEN-LAST:event_PortKeyPressed

    private void ClassNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ClassNameKeyPressed
        onStringKeyPressed("ClassName", ClassName, evt, new I_WizardActionString() {
            @Override
            public void onAction(String value) {
                emulator.setClassName(value);
            }
        });
    }//GEN-LAST:event_ClassNameKeyPressed

    private void EnabledItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_EnabledItemStateChanged
        emulator.setEnable(Enabled.isSelected());
        oneUpdate("Изменено enable="+Enabled.isSelected());
    }//GEN-LAST:event_EnabledItemStateChanged

    private void TraceItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_TraceItemStateChanged
        emulator.setTrace(Trace.isSelected());
        oneUpdate("Изменено trace="+Trace.isSelected());

    }//GEN-LAST:event_TraceItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WizardESS2EquipEmulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WizardESS2EquipEmulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WizardESS2EquipEmulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WizardESS2EquipEmulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new WizardESS2Connector().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ClassName;
    private javax.swing.JCheckBox Enabled;
    private javax.swing.JTextField Port;
    private javax.swing.JCheckBox Trace;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
