/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package romanow.abc.desktop.wizard;


import romanow.abc.core.entity.metadata.Meta2Entity;
import romanow.abc.core.entity.metadata.view.Meta2GUI2StateBox;
import romanow.abc.core.entity.metadata.view.Meta2GUIBitCheckBox;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author romanow0
 */
public class WizardMeta2GUIBitCheckBox extends WizardMeta2GUI {
    private boolean start=false;
    private Meta2GUIBitCheckBox elem;
    public WizardMeta2GUIBitCheckBox() {
        initComponents();
        }
    public void openForm(WizardBaseView parentView0, Meta2Entity entity0){
        super.openForm(parentView0,entity0);
        resizeHeight(240);
        FailMode.setVisible(false);
        elem = (Meta2GUIBitCheckBox) entity;
        WizardRegLinkPanel linkPanel = new WizardRegLinkPanel(10,120,"",elem.getRegLink(),this);
        add(linkPanel);
        start=true;
        BitNum.setText(""+elem.getBitNum());
        RemoteEnable.setSelected(elem.isRemoteEnable());
        MixedRegister.setSelected(elem.isMixedRegister());
        FailMode.setSelected(elem.isFailMode());
        TwoUnits.setSelected(elem.isTwoUnits());
        start=false;
        }
    public JCheckBox FailMode(){
        return FailMode;
        }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        BitNum = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        RemoteEnable = new javax.swing.JCheckBox();
        MixedRegister = new javax.swing.JCheckBox();
        FailMode = new javax.swing.JCheckBox();
        TwoUnits = new javax.swing.JCheckBox();

        jCheckBox1.setText("jCheckBox1");

        jCheckBox2.setText("jCheckBox2");

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(10, 84, 670, 0);

        BitNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BitNumKeyPressed(evt);
            }
        });
        getContentPane().add(BitNum);
        BitNum.setBounds(240, 150, 40, 25);

        jLabel13.setText("Бит");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(240, 130, 40, 16);

        RemoteEnable.setText("Удаленно");
        RemoteEnable.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                RemoteEnableItemStateChanged(evt);
            }
        });
        getContentPane().add(RemoteEnable);
        RemoteEnable.setBounds(290, 130, 90, 20);

        MixedRegister.setText("Рег.данных");
        MixedRegister.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                MixedRegisterItemStateChanged(evt);
            }
        });
        getContentPane().add(MixedRegister);
        MixedRegister.setBounds(380, 150, 100, 20);

        FailMode.setText("Работа/предупр.");
        FailMode.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                FailModeItemStateChanged(evt);
            }
        });
        getContentPane().add(FailMode);
        FailMode.setBounds(380, 130, 130, 20);

        TwoUnits.setText("Второй Unit");
        TwoUnits.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                TwoUnitsItemStateChanged(evt);
            }
        });
        getContentPane().add(TwoUnits);
        TwoUnits.setBounds(290, 150, 120, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        closeForm();
    }//GEN-LAST:event_formWindowClosing

    private void BitNumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BitNumKeyPressed
        onKeyPressed("bitNum", BitNum, evt, new I_WizardAction() {
            @Override
            public void onAction(int value) {
                elem.setBitNum(value);
            }
        });
    }//GEN-LAST:event_BitNumKeyPressed

    private void RemoteEnableItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_RemoteEnableItemStateChanged
        if (start)
            return;
        elem.setRemoteEnable(RemoteEnable.isSelected());
        back.onEnter("Изменено remoteEnable"+": "+elem.isRemoteEnable());
    }//GEN-LAST:event_RemoteEnableItemStateChanged

    private void MixedRegisterItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_MixedRegisterItemStateChanged
        if (start)
            return;
        elem.setMixedRegister(MixedRegister.isSelected());
        back.onEnter("Изменено mixedRegister"+": "+elem.isMixedRegister());

    }//GEN-LAST:event_MixedRegisterItemStateChanged

    private void FailModeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_FailModeItemStateChanged
        if (start)
            return;
        elem.setFailMode(FailMode.isSelected());
        back.onEnter("Изменено FailMode"+": "+elem.isFailMode());

    }//GEN-LAST:event_FailModeItemStateChanged

    private void TwoUnitsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_TwoUnitsItemStateChanged
        if (start)
        return;
        elem.setTwoUnits(TwoUnits.isSelected());
        back.onEnter("Изменено twoUnits"+": "+elem.isTwoUnits());
    }//GEN-LAST:event_TwoUnitsItemStateChanged

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BitNum;
    private javax.swing.JCheckBox FailMode;
    private javax.swing.JCheckBox MixedRegister;
    private javax.swing.JCheckBox RemoteEnable;
    private javax.swing.JCheckBox TwoUnits;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
