/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package romanow.abc.desktop.wizard;


import romanow.abc.core.entity.metadata.Meta2Entity;
import romanow.abc.core.entity.metadata.view.Meta2GUILevelMultiIndicator;

/**
 *
 * @author romanow0
 */
public class WizardMeta2GUILevelMultiIndicator extends WizardMeta2GUI {

    private Meta2GUILevelMultiIndicator elem;
    public WizardMeta2GUILevelMultiIndicator() {
        initComponents();
        }
    public void openForm(WizardBaseView parentView0, Meta2Entity entity0){
        super.openForm(parentView0,entity0);
        resizeHight(350);
        elem = (Meta2GUILevelMultiIndicator) entity;
        WizardRegLinkPanel linkPanel = new WizardRegLinkPanel(235,120,"MaxFail",elem.getMaxFail(),this);
        add(linkPanel);
        linkPanel = new WizardRegLinkPanel(235,175,"MinFail",elem.getMinFail(),this);
        add(linkPanel);
        linkPanel = new WizardRegLinkPanel(470,120,"MaxWarn",elem.getMaxWarn(),this);
        add(linkPanel);
        linkPanel = new WizardRegLinkPanel(470,175,"MinWarn",elem.getMinWarn(),this);
        add(linkPanel);
        linkPanel = new WizardRegLinkPanel(0,120,"Reg1",elem.getRegLink(),this);
        add(linkPanel);
        linkPanel = new WizardRegLinkPanel(0,175,"Reg2",elem.getRegNum2(),this);
        add(linkPanel);
        linkPanel = new WizardRegLinkPanel(0,230,"Reg3",elem.getRegNum3(),this);
        add(linkPanel);
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        W2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(10, 82, 560, 2);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(10, 120, 560, 2);

        W2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                W2KeyPressed(evt);
            }
        });
        getContentPane().add(W2);
        W2.setBounds(320, 260, 50, 25);

        jLabel13.setText("W2");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(320, 240, 40, 14);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Предупреждение");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(480, 240, 140, 14);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("Макс");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(710, 130, 70, 14);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("Мин");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(710, 185, 70, 14);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setText("Авария");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(245, 240, 60, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        closeForm();
    }//GEN-LAST:event_formWindowClosing

    private void W2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_W2KeyPressed
        onKeyPressed("W2", W2, evt, new I_WizardAction() {
            @Override
            public void onAction(int value) {
                elem.setW2(value);
            }
        });
    }//GEN-LAST:event_W2KeyPressed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField W2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
