/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package romanow.abc.desktop;

import java.util.ArrayList;
import java.util.Comparator;

import romanow.abc.core.constants.Values;
import romanow.abc.core.entity.EntityRefList;
import romanow.abc.core.entity.subjectarea.MetaDataRegister;

/**
 *
 * @author romanow
 */
public class ESSStreamRegisterSelector extends javax.swing.JPanel {
    private ArrayList<MetaDataRegister> list=new ArrayList<>();
    private MetaDataRegister selected=null;
    private I_DataRegisterValue back;
    private EntityRefList<MetaDataRegister> regisers=null;
    boolean rare=true;
    /**
     * Creates new form ESSStreamDataSelector
     */
    public ESSStreamRegisterSelector(){}
    public void init(EntityRefList<MetaDataRegister> regisers0, boolean rare0, I_DataRegisterValue back0) {
        initComponents();
        back = back0;
        regisers = regisers0;
        rare = rare0;
        refreshRegisters();
        }
    private void refreshRegisters(){
        Stream.removeAll();
        list.clear();
        regisers.sort(new Comparator<MetaDataRegister>() {
            @Override
            public int compare(MetaDataRegister o1, MetaDataRegister o2) {
                return o1.getRegNum()-o2.getRegNum();
            }
            });
        for(MetaDataRegister vv : regisers){
            boolean bb = vv.getStreamType()== Values.DataStreamRare;
            boolean bb1 = vv.getStreamType()== Values.DataStreamFrequent;
            if (rare && bb || !rare && bb1){
                list.add(vv);
                Stream.add(vv.getTitle());
                }
            }
        selected = regisers.size()==0 ? null : list.get(0);
        refreshCounters();
        }

    private void refreshCounters(){
        if (selected==null) return;
        RegNum.setText(""+selected.getRegNum());
        IDX1.setVisible(selected.getCount()!=0);
        IDX2.setVisible(selected.getCount2()!=0);
        IDX3.setVisible(selected.getCount3()!=0);
        IDX1.removeAll();
        for(int i=0;i<selected.getCount();i++)
            IDX1.add(""+(i+1));
        IDX2.removeAll();
        for(int i=0;i<selected.getCount2();i++)
            IDX2.add(""+(i+1));
        IDX3.removeAll();
        for(int i=0;i<selected.getCount3();i++)
            IDX3.add(""+(i+1));
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Stream = new java.awt.Choice();
        IDX1 = new java.awt.Choice();
        IDX2 = new java.awt.Choice();
        IDX3 = new java.awt.Choice();
        GET = new javax.swing.JButton();
        RegNumReal = new javax.swing.JTextField();
        RegNum = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        setLayout(null);

        Stream.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                StreamItemStateChanged(evt);
            }
        });
        add(Stream);
        Stream.setBounds(30, 20, 450, 20);
        add(IDX1);
        IDX1.setBounds(280, 50, 60, 20);
        add(IDX2);
        IDX2.setBounds(350, 50, 60, 20);
        add(IDX3);
        IDX3.setBounds(420, 50, 60, 20);

        GET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GETActionPerformed(evt);
            }
        });
        add(GET);
        GET.setBounds(60, 50, 40, 30);

        RegNumReal.setEnabled(false);
        add(RegNumReal);
        RegNumReal.setBounds(190, 50, 60, 25);

        RegNum.setEnabled(false);
        add(RegNum);
        RegNum.setBounds(120, 50, 60, 25);
    }// </editor-fold>//GEN-END:initComponents


    private void GETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GETActionPerformed
        if (selected==null)
            return;
        final int idx1 = selected.getCount()==0 ? 0 : IDX1.getSelectedIndex();
        final int idx2 = selected.getCount2()==0 ? 0 : IDX2.getSelectedIndex();
        final int idx3 = selected.getCount3()==0 ? 0 : IDX3.getSelectedIndex();
        int realNum = selected.getRegNumReal(idx1,idx2,idx3);
        RegNumReal.setText(""+realNum);
        back.onEnter(selected,idx1,idx2,idx3);
    }//GEN-LAST:event_GETActionPerformed

    private void StreamItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_StreamItemStateChanged
        selected = list.get(Stream.getSelectedIndex());
        refreshCounters();
    }//GEN-LAST:event_StreamItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GET;
    private java.awt.Choice IDX1;
    private java.awt.Choice IDX2;
    private java.awt.Choice IDX3;
    private javax.swing.JTextField RegNum;
    private javax.swing.JTextField RegNumReal;
    private java.awt.Choice Stream;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
