/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package romanow.abc.desktop;

import romanow.abc.core.entity.EntityRefList;
import romanow.abc.core.entity.subjectarea.MetaDataRegister;


import java.awt.*;

/**
 *
 * @author romanow
 */
public class ESSStreamRegisterView extends javax.swing.JFrame {
    private I_DataRegisterValue back;
    /**
     * Creates new form ESSStreamDataView
     */
    public ESSStreamRegisterView(EntityRefList<MetaDataRegister> regisers, boolean rare0, I_DataRegisterValue back0) {
        setUndecorated(true);
        initComponents();
        back = back0;
        setBounds(200,200,500,150);
        ESSStreamRegisterSelector selector = new ESSStreamRegisterSelector();
        selector.init(regisers,rare0,new I_DataRegisterValue(){
            @Override
            public void onEnter(MetaDataRegister register,int idz1,int idx2,int idx3) {
                back.onEnter(register,idz1,idx2,idx3);
                dispose();
                }
            });
        setTitle("Потоковые данные");
        selector.setBounds(0,0,500,100);
        add(selector);
        setVisible(true);
        }

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        g.setColor(Color.BLACK);
        g.drawRect(2,2,495,95);
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
