/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package romanow.abc.desktop;

import romanow.abc.core.I_Boolean;
import romanow.abc.core.entity.metadata.Meta2GUIView;
import romanow.abc.core.entity.metadata.render.ScreenMode;

import java.awt.*;

/**
 *
 * @author romanow
 */
public class ESSServiceGUIScreen extends javax.swing.JFrame implements I_PanelEvent {

    /**
     * Creates new form ESSServiceGUIScreen
     */
    private I_Boolean back;
    private ESSServiceGUIPanel panel;
    public ESSServiceGUIScreen(MainBaseFrame main, I_Boolean back0){
        setUndecorated(true);
        initComponents();
        setTitle("ПУ СНЭ");
        back = back0;
        setExtendedState(MAXIMIZED_BOTH);
        Dimension sSize = Toolkit.getDefaultToolkit ().getScreenSize ();
        ESSClient essClient = (ESSClient)main;
        Meta2GUIView view = essClient.currentView(false).getView();
        ScreenMode screen = new ScreenMode(false,view.getWidth(), view.getHeight(),sSize.width,sSize.height);
        setSize(sSize.width,sSize.height);
        screen.setFullScreen(true);
        panel = new ESSServiceGUIPanel(screen);
        add(panel);
        panel.initPanel(main);
        panel.setBounds(0,0,sSize.width,sSize.height-20);
        setVisible(true);
        panel.setMainForm();
        panel.setLogoutCallBack(new I_Boolean() {
            @Override
            public void onEvent(boolean bb) {
                back.onEvent(bb);
                }
            });
        panel.refresh();
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 639, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 574, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        panel.shutDown();
        back.onEvent(false);
    }//GEN-LAST:event_formWindowClosing

    @Override
    public void refresh() {
        panel.refresh();
        }
    @Override
    public void eventPanel(int code, int par1, long par2, String par3,Object oo) {
        panel.eventPanel(code,par1,par2,par3,oo);
        }
    @Override
    public void shutDown() {
        panel.shutDown();
        }
    @Override
    public boolean isMainMode() {
        return false;
        }
    @Override
    public boolean isESSMode() {
        return false;
        }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
