/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package romanow.abc.desktop;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;


import romanow.abc.core.DBRequest;
import romanow.abc.core.UniException;
import romanow.abc.core.constants.ConstValue;
import romanow.abc.core.constants.Values;
import romanow.abc.core.entity.metadata.StreamDataValue;
import romanow.abc.core.entity.metadata.StreamRegisterData;
import romanow.abc.core.entity.metadata.StreamRegisterGroup;
import romanow.abc.core.entity.subject2area.ESS2Architecture;
import romanow.abc.core.entity.subjectarea.ArchStreamDataSet;
import romanow.abc.core.entity.subjectarea.DataSet;
import romanow.abc.core.entity.subjectarea.ESSNode;
import romanow.abc.core.entity.subjectarea.MetaDataRegister;
import romanow.abc.core.utils.OwnDateTime;
import retrofit2.Call;

/**
 *
 * @author romanow
 */
public class ESSStreamDataSelector extends javax.swing.JPanel {
    private OwnDateTime time1=new OwnDateTime(false);
    private OwnDateTime time2=new OwnDateTime(false);
    private ESS2Architecture architecture;
    private StreamRegisterData data = null;
    private ESSClient main;
    private I_Value<StreamRegisterData> back;
    private ArrayList<ConstValue> modeList;
    private ConstValue selectedMode;
    private HashMap<Integer,ConstValue> compressModes;
    /**
     * Creates new form ESSStreamDataSelector
     */
    public ESSStreamDataSelector(){
        initComponents();
        }
    public void init(ESSClient base0, ESS2Architecture arch0, I_Value<StreamRegisterData> back0) {
        back = back0;
        main = base0;
        architecture = arch0;
        modeList = Values.constMap().getGroupList("DataStream");
        StreamType.removeAll();
        for(ConstValue cc : modeList)
            StreamType.add(cc.title());
        StreamRegister.removeAll();
        compressModes = Values.constMap().getGroupMapByValue("CompressMode");
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        StreamRegister = new java.awt.Choice();
        TIME1 = new javax.swing.JTextField();
        TIME2 = new javax.swing.JTextField();
        ShowGraph = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        StreamType = new java.awt.Choice();
        DataSetList = new java.awt.Choice();
        DataSourceSize = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        StreamDataOffset = new javax.swing.JTextField();
        DataValueAPI = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        DataPackedSize = new javax.swing.JTextField();
        DataPackedProc = new javax.swing.JTextField();
        DataCompressMode = new javax.swing.JTextField();
        DataValueSet = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ShowData = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setLayout(null);
        add(StreamRegister);
        StreamRegister.setBounds(10, 40, 400, 20);

        TIME1.setEnabled(false);
        TIME1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TIME1MouseClicked(evt);
            }
        });
        add(TIME1);
        TIME1.setBounds(60, 80, 110, 25);

        TIME2.setEnabled(false);
        TIME2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TIME2MouseClicked(evt);
            }
        });
        add(TIME2);
        TIME2.setBounds(180, 80, 100, 25);

        ShowGraph.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable/graph.png"))); // NOI18N
        ShowGraph.setBorderPainted(false);
        ShowGraph.setContentAreaFilled(false);
        ShowGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowGraphActionPerformed(evt);
            }
        });
        add(ShowGraph);
        ShowGraph.setBounds(370, 70, 40, 40);

        jLabel2.setText("До");
        add(jLabel2);
        jLabel2.setBounds(180, 60, 34, 14);

        jLabel3.setText("От");
        add(jLabel3);
        jLabel3.setBounds(60, 60, 14, 14);

        StreamType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                StreamTypeItemStateChanged(evt);
            }
        });
        add(StreamType);
        StreamType.setBounds(10, 10, 160, 20);

        DataSetList.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                DataSetListItemStateChanged(evt);
            }
        });
        add(DataSetList);
        DataSetList.setBounds(10, 130, 210, 20);

        DataSourceSize.setEnabled(false);
        add(DataSourceSize);
        DataSourceSize.setBounds(10, 180, 70, 25);

        jLabel4.setText("Из выборки");
        add(jLabel4);
        jLabel4.setBounds(320, 110, 70, 14);

        StreamDataOffset.setEnabled(false);
        add(StreamDataOffset);
        StreamDataOffset.setBounds(290, 80, 70, 25);

        DataValueAPI.setEnabled(false);
        add(DataValueAPI);
        DataValueAPI.setBounds(230, 130, 70, 25);

        jLabel5.setText("Смещение");
        add(jLabel5);
        jLabel5.setBounds(290, 60, 100, 14);

        jLabel6.setText("Сжатое (байт)");
        add(jLabel6);
        jLabel6.setBounds(100, 160, 90, 14);

        DataPackedSize.setEnabled(false);
        add(DataPackedSize);
        DataPackedSize.setBounds(100, 180, 70, 25);

        DataPackedProc.setEnabled(false);
        add(DataPackedProc);
        DataPackedProc.setBounds(190, 180, 70, 25);

        DataCompressMode.setEnabled(false);
        add(DataCompressMode);
        DataCompressMode.setBounds(280, 180, 110, 25);

        DataValueSet.setEnabled(false);
        add(DataValueSet);
        DataValueSet.setBounds(320, 130, 70, 25);

        jLabel7.setText("От сервера");
        add(jLabel7);
        jLabel7.setBounds(230, 110, 70, 14);

        jLabel8.setText("тип сжатия");
        add(jLabel8);
        jLabel8.setBounds(280, 160, 110, 14);

        jLabel9.setText("Исх (байт)");
        add(jLabel9);
        jLabel9.setBounds(10, 160, 70, 14);

        jLabel10.setText("% сжатия");
        add(jLabel10);
        jLabel10.setBounds(190, 160, 70, 14);

        ShowData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable/no_problem.png"))); // NOI18N
        ShowData.setBorderPainted(false);
        ShowData.setContentAreaFilled(false);
        ShowData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowDataActionPerformed(evt);
            }
        });
        add(ShowData);
        ShowData.setBounds(10, 70, 40, 40);
    }// </editor-fold>//GEN-END:initComponents


    private void ShowGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowGraphActionPerformed
        showData(true);
    }//GEN-LAST:event_ShowGraphActionPerformed

    private void refreshDataSet(){
        DataPackedSize.setText("");
        DataSourceSize.setText("");
        DataPackedProc.setText("");
        DataValueAPI.setText("");
        DataValueSet.setText("");
        DataCompressMode.setText("");
        if (DataSetList.getItemCount()==0)
            return;
        StreamDataValue value = data.getValueList().get(DataSetList.getSelectedIndex());
        DataValueAPI.setText(""+value.value);
        new APICall<DBRequest>(main){
            @Override
            public Call<DBRequest> apiFun() {
                return main.service.getEntity(main.debugToken,"ArchStreamDataSet",value.setOid,0);
                }
            @Override
            public void onSucess(DBRequest oo) {
                try {
                    ArchStreamDataSet set  = (ArchStreamDataSet) oo.get(main.gson);
                    int value = (set.getValue(data.getStreamDataOffset(),data.getRegister().doubleSize() ? 4 : 2));
                    int v1 = set.getPackedByteSize();
                    int v2 = set.getSourceByteSize();
                    DataPackedSize.setText(""+v1);
                    DataSourceSize.setText(""+v2);
                    DataPackedProc.setText(""+v1*100/v2);
                    DataCompressMode.setText(compressModes.get(set.getCompressMode()).title());
                    DataValueSet.setText(""+data.getRegister().doubleWithPower(value));
                    } catch (UniException e) {
                        System.out.println(e.toString());
                        }
                    catch (IOException e) {
                        System.out.println(e.toString());
                        }
            }
        };

    }


    private void TIME1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TIME1MouseClicked
        if (evt.getClickCount()<2) return;
        if (evt.getButton()==1){
            new CalendarView("Начало периода", new I_CalendarTime() {
                @Override
                public void onSelect(OwnDateTime time) {
                    time1 = time;
                    TIME1.setText(time1.toString2());
                    }
                });
            }
    }//GEN-LAST:event_TIME1MouseClicked

    private void TIME2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TIME2MouseClicked
        if (evt.getClickCount()<2) return;
        if (evt.getButton()==1){
            new CalendarView("Окончание периода", new I_CalendarTime() {
                @Override
                public void onSelect(OwnDateTime time) {
                    time2 = time;
                    TIME2.setText(time2.toString2());
                }
            });
        }
    }//GEN-LAST:event_TIME2MouseClicked

    private void StreamTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_StreamTypeItemStateChanged
        int idx = StreamType.getSelectedIndex();
        selectedMode = modeList.get(idx);
        StreamRegister.removeAll();
        if (selectedMode.value()==Values.DataStreamNone){
            return;
            }
        ArrayList<StreamRegisterGroup> list = architecture.getStreamRegisterList(selectedMode.value());
        for(StreamRegisterGroup group : list)
            for(StreamRegisterData registerData : group.getList())
                StreamRegister.add(registerData.getTitle());
        }//GEN-LAST:event_StreamTypeItemStateChanged

    private void DataSetListItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_DataSetListItemStateChanged
        refreshDataSet();
    }//GEN-LAST:event_DataSetListItemStateChanged

    private void showData(boolean graph){
        if (StreamRegister.getItemCount()==0)
            return;
        final  int logNum = StreamRegister.getSelectedIndex();
        data = architecture.getStreamRegisterByLogNum(selectedMode.value(),logNum);
        StreamDataOffset.setText(""+data.getRegOffset());
        if (data==null)
            return;
        new APICall<ArrayList<StreamDataValue>>(main){
            @Override
            public Call<ArrayList<StreamDataValue>> apiFun() {
                return main.service2.getStreamData(main.debugToken,selectedMode.value(),logNum,time1.timeInMS(),time2.timeInMS());
            }
            @Override
            public void onSucess(ArrayList<StreamDataValue> oo) {
                data.setValueList(oo);
                if (graph)
                    back.onEnter(data);
                else
                    {
                    DataSetList.removeAll();
                    for(StreamDataValue vv : oo){
                        DataSetList.add("["+vv.setOid+"] "+new OwnDateTime(vv.timeStamp).toString2());
                        }
                    refreshDataSet();
                    }
                }
            };
        }

    private void ShowDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowDataActionPerformed
        showData(false);
    }//GEN-LAST:event_ShowDataActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DataCompressMode;
    private javax.swing.JTextField DataPackedProc;
    private javax.swing.JTextField DataPackedSize;
    private java.awt.Choice DataSetList;
    private javax.swing.JTextField DataSourceSize;
    private javax.swing.JTextField DataValueAPI;
    private javax.swing.JTextField DataValueSet;
    private javax.swing.JButton ShowData;
    private javax.swing.JButton ShowGraph;
    private javax.swing.JTextField StreamDataOffset;
    private java.awt.Choice StreamRegister;
    private java.awt.Choice StreamType;
    private javax.swing.JTextField TIME1;
    private javax.swing.JTextField TIME2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
